- name: Configure Chrony on Proxmox and Kubernetes Nodes
  hosts: all
  become: yes
  tasks:
    - name: Install chrony
      apt:
        name: chrony
        state: present

    - name: Deploy chrony.conf
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart chrony

  handlers:
    - name: restart chrony
      service:
        name: chrony
        state: restarted

# Special task for Proxmox nodes: Verify time sync with each other
- name: Verify time sync on Proxmox nodes
  hosts: proxmox
  become: true
  tasks:
    - name: Check the status of chrony
      command: chronyc tracking
      register: chrony_status

    - name: Debug the chrony status
      debug:
        msg: "{{ chrony_status.stdout }}"
